### ISSUE TITLE
What is the command for adding new screen?

### ISSUE THREAD

**Issue by parvbhullar** [cristhianescobar/generator-android-starter#30]

**Comment by cristhianescobar** [comment]
Hi @parvbhullar we have removed Flow and Mortar along with those commands for now because it's somewhat of a learning curve. This will allow the users decide what pattern they want to go with instead of forcing to use Mortar and Flow.

**Comment by parvbhullar** [comment]
Hi So If I rebuild app using the same it won't include Flow & Morter? Instead I can use my preferred lib/pattern.

**Comment by cristhianescobar** [comment]
Correct @parvbhullar
